version: "3.9"

services:
  aggregator:
    build: .
    container_name: aggregator
    ports:
      - "8080:8080"
    networks:
      - app-network

  publisher:
    build: .
    container_name: publisher
    command: python publisher.py
    depends_on:
      - aggregator
    networks:
      - app-network

networks:
  app-network: